"""Sponsor logos for the site. Files only, no database.

  npm run sponsors          (python3, Pillow and numpy)

For every image in design/sponsors-raw/ (named after the sponsor, e.g. zimdra-automobiles.png):
  - the white background connected to the image edges becomes transparent; white enclosed by the
    artwork (e.g. details inside the Zimdra emblem) stays, and the logo itself is never edited,
    cropped into or recoloured
  - the empty margins are trimmed, leaving a little room around the logo
  - written to public/sponsors/<name>.webp at 120 px tall (sharp at up to 40 CSS px on 3x screens)
Then src/data/sponsor-sizes.ts (generated) gets each file's width and height, so the page can reserve
the space before a logo loads. Which sponsors are shown, in what order, is src/data/sponsors.ts.
"""
from collections import deque
from pathlib import Path

import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
RAW = ROOT / "design/sponsors-raw"
OUT = ROOT / "public/sponsors"
SIZES = ROOT / "src/data/sponsor-sizes.ts"
HEIGHT = 120
WHITE = 226  # every channel at least this: background white (allows the faint grey gradients in scans)
MARGIN = 0.04  # room kept around the logo, as a share of its height


def edge_background(rgb: np.ndarray) -> np.ndarray:
    """Near-white pixels connected to the image edges (4-neighbour flood fill from every edge)."""
    h, w, _ = rgb.shape
    white = (rgb >= WHITE).all(axis=2)
    bg = np.zeros((h, w), dtype=bool)
    queue: deque[tuple[int, int]] = deque()
    for x in range(w):
        for y in (0, h - 1):
            if white[y, x] and not bg[y, x]:
                bg[y, x] = True
                queue.append((y, x))
    for y in range(h):
        for x in (0, w - 1):
            if white[y, x] and not bg[y, x]:
                bg[y, x] = True
                queue.append((y, x))
    while queue:
        y, x = queue.popleft()
        for ny, nx in ((y - 1, x), (y + 1, x), (y, x - 1), (y, x + 1)):
            if 0 <= ny < h and 0 <= nx < w and white[ny, nx] and not bg[ny, nx]:
                bg[ny, nx] = True
                queue.append((ny, nx))
    return bg


def process(path: Path) -> tuple[str, int, int]:
    im = Image.open(path).convert("RGBA")
    arr = np.array(im)
    bg = edge_background(arr[:, :, :3]) | (arr[:, :, 3] < 10)
    arr[bg, 3] = 0
    logo = Image.fromarray(arr)
    left, top, right, bottom = Image.fromarray((~bg).astype(np.uint8) * 255).getbbox()
    pad = round((bottom - top) * MARGIN)
    logo = logo.crop((max(0, left - pad), max(0, top - pad), min(im.width, right + pad), min(im.height, bottom + pad)))
    w = round(logo.width * HEIGHT / logo.height)
    logo = logo.resize((w, HEIGHT), Image.LANCZOS)
    OUT.mkdir(parents=True, exist_ok=True)
    name = path.stem.lower()
    logo.save(OUT / f"{name}.webp", quality=90, alpha_quality=95, method=6)
    enclosed = int((arr[:, :, :3] >= WHITE).all(axis=2).sum() - bg.sum())
    print(f"  {name}.webp  {w}x{HEIGHT}  (aspect {w / HEIGHT:.2f}; {enclosed} white pixels inside the artwork kept)")
    return name, w, HEIGHT


def main() -> None:
    files = sorted(p for p in RAW.iterdir() if p.suffix.lower() in (".png", ".jpg", ".jpeg", ".webp"))
    print(f"Sponsor logos from {RAW.relative_to(ROOT)}:")
    sizes = [process(p) for p in files]
    lines = "\n".join(f'  "{n}": [{w}, {h}],' for n, w, h in sizes)
    SIZES.write_text(
        "// Generated by scripts/sponsor-logos.py (npm run sponsors). Don't edit.\n"
        "// Width and height of each processed logo in public/sponsors/, by file name.\n"
        f"export const SPONSOR_SIZES: Record<string, [number, number]> = {{\n{lines}\n}};\n"
    )
    print(f"Wrote {SIZES.relative_to(ROOT)}.")


main()
