// Generated by scripts/sponsor-logos.py (npm run sponsors). Don't edit.
// Width and height of each processed logo in public/sponsors/, by file name.
export const SPONSOR_SIZES: Record<string, [number, number]> = {
  "coca-cola": [350, 120],
  "zimdra-automobiles": [802, 120],
};
